// Selected work. Pulled from https://oluwatobi-akinrimisi.netlify.app/ (auto-fetched
// and summarized — double-check each description against the live project before
// treating it as final copy). `year` and `role` weren't listed on the source site,
// so they're left as bracket placeholders — fill in and set isPlaceholder to false
// once confirmed. The grid layout (featured / pair / horizontal) is assigned
// automatically by index — see lib/work-layout.ts — so you can usually just add or
// reorder entries without touching the UI.

import type { Project } from "./types";

export const projects: Project[] = [
  {
    slug: "ajoti",
    name: "Ajoti",
    description: "Digital ROSCA platform that modernizes traditional cooperative savings.",
    role: "Co-Founder · Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript", "Tailwind"],
    category: "Fintech",
    image: "/images/projects/ajoti.png",
    externalUrl: "https://ajoti.com/",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "beafrique",
    name: "Beafrique",
    description: "E-commerce platform for African women's fashion with global Stripe payments.",
    role: "Full-Stack Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript", "Stripe"],
    category: "E-commerce",
    image: "/images/projects/beafrique.jpeg",
    externalUrl: "https://beafrique.netlify.app/",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "esemie-website",
    name: "Esemie",
    description: "Performance-minded, SEO-friendly marketing site for a business tool.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "Gatsby"],
    category: "Marketing",
    image: "/images/projects/esemie-hero.png",
    externalUrl: "https://www.esemie.io",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "alaje-merchant",
    name: "Alaje Merchant",
    description: "Modern payment gateway dashboard for merchants — secure, fast online payments.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "Payments",
    image: "/images/projects/alajeMerchant.png",
    externalUrl: "https://alaje-web-merchant.vercel.app/login",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "alaje-admin",
    name: "Alaje Admin",
    description: "Admin console for payment gateway operations and merchant management.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "Admin",
    image: "/images/projects/alajeAdmin.png",
    externalUrl: "https://alaje-admin.vercel.app/login",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "esemie-business-app",
    name: "Esemie Business App",
    description: "Invoicing, expenses and reporting for small businesses.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript", "Zustand", "Supabase"],
    category: "SaaS",
    image: "/images/projects/esemie-hero.png",
    externalUrl: "https://app.esemie.io/",
    hasCaseStudy: true,
    isPlaceholder: false,
  },
  {
    slug: "valuejet",
    name: "ValueJet",
    description: "Customer portal with authentication and account flows for an airline.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "Aviation",
    image: "/images/projects/valuejet.png",
    externalUrl: "https://valuejet-fe-main.vercel.app/signin",
    hasCaseStudy: false,
    isPlaceholder: false,
  },
  {
    slug: "family-court-app",
    name: "Family Court App",
    description: "Streamlines case management, document handling, and scheduling.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "Workflow",
    image: "/images/projects/courtapp.png",
    externalUrl: "https://familycourt.rv.gov.ng/",
    hasCaseStudy: false,
    isPlaceholder: false,
  },
  {
    slug: "faith-hospital",
    name: "Faith Specialist Hospital",
    description: "Appointment booking and patient information flows for a hospital.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "Healthcare",
    image: "/images/projects/faithhospital.png",
    externalUrl: "https://faith-specialist-hospital.netlify.app/",
    hasCaseStudy: false,
    isPlaceholder: false,
  },
  {
    slug: "ilearn",
    name: "ILEARN",
    description: "Tutor-student matching with simple flows and a responsive UI.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "EdTech",
    image: "/images/projects/ilearn.png",
    externalUrl: "https://ilearn-sq012-node.netlify.app",
    hasCaseStudy: false,
    isPlaceholder: false,
  },
  {
    slug: "r2blaze",
    name: "R2Blaze",
    description: "E-commerce store for premium wristwatches, built with product browsing, search and checkout.",
    role: "Frontend Developer",
    year: "[YEAR]",
    tech: ["React", "TypeScript"],
    category: "E-commerce",
    image: "/images/projects/r2blaze.png",
    externalUrl: "https://r2blaze.com",
    hasCaseStudy: false,
    isPlaceholder: false,
  },
];
